backend/produto/urls.py
from django.urls import path

from backend.produto import views as v

app_name = 'produto'


urlpatterns = [
    path('', v.ProdutoListView.as_view(), name='produto_list'),  # noqa E501
    path('detail/<int:pk>/', v.ProdutoDetailView.as_view(), name='produto_detail'),  # noqa E501
    path('create/', v.produto_create, name='produto_create'),  # noqa E501
    path('update/<int:pk>/',v.produto_update,name='produto_update'),
    path('delete/<int:pk>/',v.produto_delete,name='produto_delete'),
    path('add-row/', v.add_row_produto_items_hx, name='add_row_produto_items_hx'),  # noqa E501
    path('produto-search/', v.produto_items_search, name='produto_items_search'),  # noqa E501
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('crm/', include('backend.crm.urls', namespace='crm')),
    path('produto/', include('backend.produto.urls', namespace='produto')),
    path('orcamento/', include('backend.orcamento.urls', namespace='orcamento')),
    path('logistica/', include('backend.logistica.urls', namespace='logistica')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/produto/models.py
from django.db import models
from django.urls import reverse

from backend.core.models import Active, CreatedBy, DeletedBy, TimeStampedModel


class Produto(TimeStampedModel, CreatedBy, DeletedBy, Active):
    FORNECEDORES_CHOICE=[
        ('REALCE','REALCE'),
        ('RINCAO','RINCAO'),
        ('DAF','DAF'),
        ('FORMACASA','FORMACASA'),
        ('GAZIN','GAZIN'),
        ('MV','MV'),
        ('MS DECOR','MS DECOR'),
        ('ANJOS COLCHOES','ANJOS COLCHOES'),
        ('DORIGON','DORIGON'),
        ('SALA VIPP','SALA VIPP'),
        ('ZU HOUSE','ZU HOUSE'),
        ('ARTE CUBICA','ARTE CUBICA'),
        ('CRISTALFLEX','CRISTALFLEX'),
        ('MACROSUL','MACROSUL'),
        ('MAMBEL','MAMBEL'),
        ('LED','LED'),
        ('COLOMI','COLOMI'),
        ('DARCY','DARCY'),
        ('LAFF','LAFF'),
        ('ROGAR','ROGAR'),
        ('METTA MOBILI','METTA MOBILI'),
        ('MEYER','MEYER'),
        ('SALKA','SALKA'),
        ('ELEMIS','ELEMIS'),
        ('MONTE BELO','MONTE BELO'),
        ('NIRUMA','NIRUMA'),
        ('WANG E CIA','WANG E CIA'),
        ('AVOZZANI','AVOZZANI'),
        ('PREVILEGE','PREVILEGE'),
        ('SCHNEIDER','SCHNEIDER'),
        ('VITORIA DESIGNER','VITORIA DESIGNER'),

    ]
    codigo = models.CharField('Código',max_length=100)
    titulo = models.CharField('Descrição', max_length=100)
    categoria = models.ForeignKey(
        'Categoria',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    marca = models.ForeignKey(
        'Marca',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    preco = models.DecimalField(
        'Preço_a_Vista',
        max_digits=6,
        decimal_places=2,
        blank=True,
        null=True
    )
    preco_cred = models.DecimalField(
        'Preço_a_Credito',
        max_digits=6,
        decimal_places=2,
        blank=True,
        null=True
    )
    estoque_minimo = models.PositiveIntegerField('Estoque Mínimo', null=True, blank=True)  # noqa E501
    estoque_atual = models.PositiveIntegerField('Estoque Atual', null=True, blank=True)  # noqa E501
    fabrica = models.CharField(max_length=255,choices=FORNECEDORES_CHOICE,null=True,blank=True)
    tamanho = models.DecimalField(max_digits=10,decimal_places=2,blank=True,null=True)
    tecido = models.CharField(max_length=255,blank=True,null=True)
    madeira = models.CharField(max_length=255,blank=True,null=True)

    class Meta:
        ordering = ('titulo',)
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    def __str__(self):
        return f'{self.titulo}'

    def get_absolute_url(self):
        return reverse('produto:produto_detail', kwargs={'pk': self.pk})


class Patrimonio(TimeStampedModel, CreatedBy, DeletedBy, Active):
    titulo = models.CharField('Título', max_length=100, unique=True)
    produto = models.ForeignKey(
        Produto,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='patrimonios',
    )

    class Meta:
        ordering = ('titulo',)
        verbose_name = 'Patrimônio'
        verbose_name_plural = 'Patrimônios'

    def __str__(self):
        return f'{self.titulo}'


class Marca(TimeStampedModel, CreatedBy, DeletedBy, Active):
    titulo = models.CharField(max_length=100, unique=True)
    modelo = models.CharField(max_length=200)

    class Meta:
        ordering = ('titulo',)

    def __str__(self):
        return f'{self.titulo}'


class Categoria(TimeStampedModel, CreatedBy, DeletedBy, Active):
    titulo = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ('titulo',)

    def __str__(self):
        return f'{self.titulo}'

backend/produto/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Categoria, Marca, Patrimonio, Produto


class ProdutoForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Produto
        fields = (
            'codigo',
            'titulo',
            'categoria',
            'marca',
            'preco',
            'preco_cred',
            'estoque_atual',
            'fabrica',
            'tamanho',
            'tecido',
            'madeira',
        )


class PatrimonioForm(forms.ModelForm):
    id = forms.IntegerField()

    class Meta:
        model = Patrimonio
        fields = ('produto', 'id', 'titulo')

    def __init__(self, *args, **kwargs):
        super(PatrimonioForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['produto'].label = ''
        self.fields['produto'].widget = forms.HiddenInput()

        self.fields['id'].label = ''
        self.fields['id'].widget = forms.HiddenInput()


class CategoriatForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ('titulo', 'active')

    def __init__(self, *args, **kwargs):
        super(CategoriatForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field = self.fields.get(field_name)
            field.widget.attrs.update({'placeholder': field.label})
            field.widget.attrs['class'] = 'form-control'

        self.fields['active'].widget.attrs['class'] = 'form-check-input'


class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ('titulo', 'modelo', 'active')

    def __init__(self, *args, **kwargs):
        super(MarcaForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field = self.fields.get(field_name)
            field.widget.attrs.update({'placeholder': field.label})
            field.widget.attrs['class'] = 'form-control'

        self.fields['active'].widget.attrs['class'] = 'form-check-input'


ProdutoItemsFormset = inlineformset_factory(
    Produto,
    Patrimonio,
    form=PatrimonioForm,
    extra=0,
    can_delete=False,
    min_num=1,
    validate_min=True,
)

backend/produto/views.py
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import DetailView, ListView

from .forms import PatrimonioForm, ProdutoForm, ProdutoItemsFormset
from .models import Produto


class ProdutoListView(LRM, ListView):
    model = Produto


class ProdutoDetailView(LRM, DetailView):
    model = Produto


def produto_create(request):
    template_name = 'produto/produto_form.html'
    produto_instance = Produto()

    form = ProdutoForm(request.POST or None, instance=produto_instance, prefix='main')  # noqa E501
    formset = ProdutoItemsFormset(request.POST or None, instance=produto_instance, prefix='items')  # noqa E501

    if request.method == 'POST':
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect('produto:produto_list')

    context = {'form': form, 'formset': formset}
    return render(request, template_name, context)

def produto_update(request, pk):
    template_name = 'produto/produto_form.html'
    produto_instance = Produto.objects.get(pk=pk)

    form = ProdutoForm(request.POST or None, instance=produto_instance, prefix='main')  # noqa E501
    formset = ProdutoItemsFormset(request.POST or None, instance=produto_instance, prefix='items')  # noqa E501

    if request.method == 'POST':
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect('produto:produto_list')

    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, template_name, context)

def produto_delete(request, pk):
    order_item = Produto.objects.get(pk=pk)
    order_item.delete()
    return redirect('produto:produto_list')


def add_row_produto_items_hx(request):
    template_name = 'produto/hx/row_produto_items_hx.html'
    form = PatrimonioForm()
    context = {'produto_item_form': form}
    return render(request, template_name, context)


def order_item_delete(request, pk):
    order_item = Produto.objects.get(pk=pk)
    order_item.delete()
    return HttpResponse('')


def produto_items_search(request):
    template = 'produto/hx/search-results.html'
    search_text = request.GET.get('search')
    results = Produto.objects.filter(titulo__icontains=search_text)
    context = {"results": results}
    return render(request, template, context)

backend/produto/templates/produto/produto_detail.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <h2>
      {{ object }}
      <a href="{% url 'produto:produto_list' %}">
        <button type="button" class="btn btn-link">
          <span class="fw-semibold">Voltar</span>
        </button>
      </a>
    </h2>
    <div class="row">
      <div class="col-6">

        <div class="mt-4">
          <p class="text-muted mb-1">Código:</p>
          <h5 class="font-size-14">{{ object.codigo }}</h5>
        </div>

        <div class="mt-4">
          <p class="text-muted mb-1">Título:</p>
          <h5 class="font-size-14">{{ object.titulo }}</h5>
        </div>

        <div class="mt-4">
          <p class="text-muted mb-1">Categoria:</p>
          <h5 class="font-size-14">{{ object.categoria }}</h5>
        </div>

        <div class="mt-4">
          <p class="text-muted mb-1">Marca:</p>
          <h5 class="font-size-14">{{ object.marca }}</h5>
        </div>

        <div class="mt-4">
          <p class="text-muted mb-1">Preço de Compra:</p>
          <h5 class="font-size-14">R$ {{ object.preco_compra }}</h5>
        </div>

        <div class="mt-4">
          <p class="text-muted mb-1">Preço da Diária:</p>
          <h5 class="font-size-14">R$ {{ object.preco_diaria }}</h5>
        </div>

        <div class="mt-4">
          <p class="text-muted mb-1">Estoque Mínimo:</p>
          <h5 class="font-size-14">{{ object.estoque_minimo }}</h5>
        </div>

        <div class="mt-4">
          <p class="text-muted mb-1">Estoque Atual:</p>
          <h5 class="font-size-14">{{ object.estoque_atual }}</h5>
        </div>

        <div class="mt-4">
          <p class="text-muted mb-1">Ativo:</p>
          {% if object.active %}
            <i class="mdi mdi-check-circle-outline text-success"></i>
          {% else %}
            <i class="mdi mdi-close-circle-outline text-danger"></i>
          {% endif %}
        </div>

      </div>
      <div class="col-6">
        <h4>OBSERVAÇÕES</h4>
        <ul>
          {% for item in object.patrimonios.all %}
            <li class="font-size-14">{{ item.titulo }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </main>
{% endblock content %}

backend/produto/templates/produto/produto_form.html
{% extends 'base.html'%}
{% load static %}
{% load widget_tweaks %}

{% block content %}
  <h4>Cadastrar Produto</h4>
  <form action="." method="POST">
    {% csrf_token %}

    <div class="form-row">
      <div class="row">
        {% for field in form.visible_fields %}
          <div class="form-group col-sm-3">
            <label>{{ field.label }}</label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
              <span class="text-muted">{{ error }}</span>
            {% endfor %}
          </div>
        {% endfor %}
      </div>
    </div>

    {{ formset.management_form }}

    <div class="row">
      <div class="col-sm-12">
        <legend class="legend">OBSERVAÇÕES</legend>
        <div>
          <button
            id="addItem"
            class='btn btn-primary mb-2'
            hx-get="{% url 'produto:add_row_produto_items_hx' %}"
            hx-target="#produto"
            hx-swap="beforeend"
          >Adicionar</button>
        </div>
      </div>
    </div>

    <div id="produto">

      {% for produto_item_form in formset %}
        <div class="row d-flex align-items-end">
          <div class="col-md-6">
            <div id="item-{{ forloop.counter0 }}" class="form-group">
              {% render_field produto_item_form.produto data-field='produto' %}

              <label>{{ produto_item_form.titulo.label }}</label>
              {% render_field produto_item_form.titulo class="form-control" data-field='titulo' %}
            </div>
          </div>
          <div class="col-md-6">
            <span class="span-is-link no ml-2" onclick="removeRow()">
              <i class="fa fa-times fa-lg"></i>
            </span>
          </div>
        </div>
      {% endfor %}

    </div>

    <div class="mt-4">
      <button class='btn btn-primary' type="submit">Salvar</button>
      <button type="button" class="btn btn-danger">Cancelar</button>
    </div>

  </form>
{% endblock content %}

{% block js %}
  <script src="{% static 'js/produto.js' %}"></script>

  <script>
    // Necessário por causa do delete
    document.body.addEventListener('htmx:configRequest', (event) => {
      event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    });
  </script>

{% endblock js %}

backend/produto/templates/produto/produto_list.html
{% extends 'base.html'%}
{% load static %}

{% block content %}

  <div class="card">
    <div class="d-flex bd-highlight">
      <div class="card-body">

        <h4 class="card-title mb-3">
          Produtos
          <a href="{% url 'produto:produto_create' %}">
            <button type="button" class="btn btn-link shadow-none">
              Cadastrar
            </button>
          </a>
          <div class="dropdown d-inline">
            <a class="dropdown-toggle text-muted me-3 mb-3 align-middle" href="#" data-bs-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <button type="button" class="btn btn-link shadow-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-search icon-sm">
                  <circle cx="11" cy="11" r="8"></circle>
                  <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                </svg><span>Buscar</span>
              </button></a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0">
              <form class="p-2">
                <div class="search-box">
                  <div class="position-relative">

                    <input type="text" name="search" class="form-control rounded bg-light border-0"
                      hx-get="{% url 'produto:produto_items_search' %}"
                      hx-trigger="keyup changed delay:250ms, search"
                      hx-target="#search-results" placeholder="buscando...">

                    <span id="search-results"></span>

                  </div>
                </div>
              </form>
            </div>

          </div>
        </h4>

        <div class="table-responsive">
          <table class="table table-hover mb-0 align-middle">
            <thead class="bg-light">
              <tr>
                <th class="rounded-start" style="width: 15px;">
                  <div class="form-check">
                    <input class="form-check-input font-size-16" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault"> </label>
                  </div>
                </th>
                <th class="text-center">Código</th>
                <th>Descrição</th>
                <th>Fabrica</th>
                <th>Tecido</th>
                <th>Madeira</th>
                <th>Preço a Vista</th>
                <th>Preço a Crédito</th>
                <th class="text-center">Tamanho</th>
                <th class="text-center">Estoque Atual</th>
                <th class="text-center">Ativo</th>
                <th></th>
              </tr>
              <!-- end tr -->
            </thead>
            <!-- end thead -->
            <tbody>
              {% for object in object_list %}
                <tr>
                  <td>
                    <div class="form-check">
                      <input class="form-check-input font-size-16" type="checkbox" value="" id="flexCheckexampleone">
                      <label class="form-check-label" for="flexCheckexampleone">
                      </label>
                    </div>
                  </td>
                  <td class="text-center">{{ object.codigo }}</td>
                  <td>
                    <a href="{{ object.get_absolute_url }}">{{ object.titulo }}</a>
                  </td>
                  <td>{{ object.fabrica|default:"---" }}</td>
                  <td>{{ object.tecido|default:"---" }}</td>
                  <td>{{ object.madeira|default:"---" }}</td>
                  <td>
                    R$ <span style="float: right">{{ object.preco|default:"---" }}</span>
                  </td>
                  <td>
                    R$ <span style="float: right">{{ object.preco_cred|default:"---" }}</span>
                  </td>
                  <td class="text-center">{{ object.tamanho|default:"---" }}</td>
                  <td class="text-center">{{ object.estoque_atual|default:"---" }}</td>
                  <td>
                    <div class="text-center">
                      {% if object.active %}
                        <i class="mdi mdi-check-circle-outline text-success"></i>
                      {% else %}
                        <i class="mdi mdi-close-circle-outline text-danger"></i>
                      {% endif %}
                    </div>
                  </td>
                  <td style="min-width: 70px">
                    <span>
                      <a href="{% url 'produto:produto_update' object.pk %}"><i class="mdi mdi-pencil text-success me-1"></i></a>
                    </span>
                    <span>
                      <a href="{% url 'produto:produto_delete' object.pk %}"><i class="mdi mdi-trash-can text-danger me-1"></i></a>
                    </span>
                  </td>
                </tr>
              {% endfor %}
              <!-- end /tr -->
            </tbody><!-- end tbody -->
          </table><!-- end table -->
        </div>
      </div>
    </div>
  </div>
{% endblock content %}